# Schema
DB = "db"
Name = "name"
Tables = "tables"
Table = "table"
Columns = "columns"
Column = "column"
Attributes = "attributes"
Initials = "initials"
Initial = "initial"
InitialValue = "initialvalue"
Value = "value"
PrimaryKey = "primarykey"
